/**
 * Generates the browser-safe bundle of controls + modules from the YAML
 * source. Run after editing any YAML file under data/:
 *
 *   pnpm --filter @iwc/controls build:bundle
 *
 * The generated file is committed; CI re-runs this script and fails if
 * the working tree drifts (see test/bundle.test.ts), so the YAML always
 * stays in sync with what the browser ships.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  loadAllControls,
  loadAllSamples,
  loadModules,
  DEFAULT_DATA_DIR,
} from '../src/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, '..', 'src', 'bundle', 'catalogue.gen.ts');

async function main() {
  const [controls, modules, samples] = await Promise.all([
    loadAllControls(DEFAULT_DATA_DIR),
    loadModules(DEFAULT_DATA_DIR),
    loadAllSamples(DEFAULT_DATA_DIR),
  ]);

  const banner = `// AUTOGENERATED by scripts/build-bundle.ts. Do not edit.
// Source: packages/controls/data/**/*.yaml + reference-samples/*.json
// Run \`pnpm --filter @iwc/controls build:bundle\` to refresh.

import type {
  ControlsCatalogue,
  ModuleMetadata,
  ReferenceSample,
} from '../schema';
`;

  const body = `
export const CONTROLS_BUNDLE: ControlsCatalogue = ${JSON.stringify(
    controls,
    null,
    2,
  )};

export const MODULES_BUNDLE: ModuleMetadata[] = ${JSON.stringify(modules, null, 2)};

export const SAMPLES_BUNDLE: ReferenceSample[] = ${JSON.stringify(samples, null, 2)};
`;

  writeFileSync(outFile, banner + body, 'utf8');
  console.log(
    `Wrote ${controls.length} controls, ${modules.length} modules, and ${samples.length} samples to ${outFile}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
