/**
 * Generates the browser-safe bundle of controls + modules from the YAML
 * source. Run after editing any YAML file under data/:
 *
 *   pnpm --filter @iwc/controls build:bundle
 *
 * The generated file is committed; CI re-runs this script and fails if
 * the working tree drifts (see test/bundle.test.ts), so the YAML always
 * stays in sync with what the browser ships.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  loadAllControls,
  loadAllSamples,
  loadModules,
  DEFAULT_DATA_DIR,
} from '../src/index.js';
// Source of truth for "which controls have an automated check". Imported
// from the engine package at build time so the catalogue can mark each
// row without forcing the web app to depend on @iwc/engine at runtime.
import { BUILTIN_CHECK_IDS } from '../../engine/src/checks/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, '..', 'src', 'bundle', 'catalogue.gen.ts');

async function main() {
  const [controls, modules, samples] = await Promise.all([
    loadAllControls(DEFAULT_DATA_DIR),
    loadModules(DEFAULT_DATA_DIR),
    loadAllSamples(DEFAULT_DATA_DIR),
  ]);

  // Sorted for stable diffs whenever the engine adds/removes a check.
  const autoTestedIds = [...BUILTIN_CHECK_IDS].sort();

  const banner = `// AUTOGENERATED by scripts/build-bundle.ts. Do not edit.
// Source: packages/controls/data/**/*.yaml + reference-samples/*.json
// Run \`pnpm --filter @iwc/controls build:bundle\` to refresh.

import type {
  ControlsCatalogue,
  ModuleMetadata,
  ReferenceSample,
} from '../schema';
`;

  const body = `
export const CONTROLS_BUNDLE: ControlsCatalogue = ${JSON.stringify(
    controls,
    null,
    2,
  )};

export const MODULES_BUNDLE: ModuleMetadata[] = ${JSON.stringify(modules, null, 2)};

export const SAMPLES_BUNDLE: ReferenceSample[] = ${JSON.stringify(samples, null, 2)};

/**
 * Control ids that have an automated check registered in @iwc/engine.
 * Sourced from the engine's BUILTIN_CHECK_IDS at bundle build time so
 * the web app can mark each catalogue row "auto-tested" without
 * depending on the engine at runtime.
 */
export const AUTO_TESTED_IDS: readonly string[] = ${JSON.stringify(autoTestedIds, null, 2)};
`;

  writeFileSync(outFile, banner + body, 'utf8');
  console.log(
    `Wrote ${controls.length} controls, ${modules.length} modules, ${samples.length} samples, and ${autoTestedIds.length} auto-tested ids to ${outFile}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
